
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: eureka-client-service
server:
  port: 8081

management:
  security:
    enabled: false
  server:
    port: 9000

